# Site settings
title: Lucas Lamo - Software Developer
description: Software developer since 2008
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "lucaslamo.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Lucas Lamo
user_description: I am Lucas Lamo, curious and passionate about technology, I work with software development since 2008, with skills in Delphi, PHP, Python, Ruby, Shell, Linux, Pentest, a bit of AWS
user_title: Software Developer
email: dev@lucaslamo.com
github_username:  lucaslamo

# Google-analytics
google-analytics:
  id: "UA-120202386-1"

exclude: ['package.json', 'src' , 'node_modules']
